version: '3.3'

services:
  peertube:
    image: chocobozzz/peertube:production-bullseye
    environment:
      - PEERTUBE_DB_USERNAME=peertube
      - PEERTUBE_DB_PASSWORD=peertube
      - PEERTUBE_DB_HOSTNAME=postgres
      - PEERTUBE_REDIS_HOSTNAME=redis
      - PEERTUBE_WEBSERVER_HOSTNAME=umbrel.local
      - PEERTUBE_WEBSERVER_PORT=9001
      - PEERTUBE_TRUST_PROXY=["loopback", "linklocal", "uniquelocal"]
      - PEERTUBE_ADMIN_EMAIL=admin@example.com
      - PEERTUBE_SECRET=supersecretkeyChangeMe
    ports:
      - "9001:9000"
    volumes:
      - ${APP_DATA_DIR}/data/peertube:/var/www/peertube/storage
      - ${APP_DATA_DIR}/config/peertube:/var/www/peertube/config
    depends_on:
      - postgres
      - redis
    restart: on-failure

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=peertube
      - POSTGRES_PASSWORD=peertube
      - POSTGRES_DB=peertube_prod
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:6-alpine
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    restart: on-failure
